name: Deploy FastAPI to VPS

# on:
#   push:
#     tags:
#       - "v*"

on:
  push:
    branches:
      - '**'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to VPS
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          port: 22
          script: |
            # Verify the deploy.sh script exists
            if [ -f /root/server/lexomat/deploy.sh ]; then
              echo "deploy.sh found"
              cd /root/server/lexomat && ./deploy.sh
            else
              echo "deploy.sh not found"
              exit 1
            fi