name: Deploy FastAPI to VPS

# on:
#   push:
#     tags:
#       - "v*"

on:
  push:
    branches:
      - '**'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to VPS
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          port: 22
          script: |
            cd ./server/lexomat/backend/
            git pull origin main
            uv sync
            sudo supervisorctl restart lexomat
