name: Deploy FastAPI to VPS

# on:
#   push:
#     tags:
#       - "v*"

on:
  push:
    branches:
      - '**'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to VPS
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          port: 22
          script: |
            # Additional inline deployment commands:
            echo "Changing directory to the backend..."
            cd /root/server/lexomat/backend/ || { echo "Directory not found"; exit 1; }

            echo "Pulling latest code from origin main..."
            git pull origin main

            echo "Updating PATH to include local binaries..."
            export PATH="$HOME/.local/bin:$PATH"

            echo "Syncing project environment using uv..."
            uv sync

            echo "Restarting FastAPI via supervisor..."
            sudo supervisorctl restart lexomat

            echo "Deployment complete."